version: '3'
services:
  postgres:
    image: "postgres:11"
    container_name: "tiny_postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=tiny_task
      - POSTGRES_USER=tiny_task
      - POSTGRES_PASSWORD=demo123
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
