hibernate:
    dialect: org.hibernate.dialect.MySQLDialect
    format_sql: true
    id:
        new_generator_mappings: false
    show_sql: true
logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE
server:
    port: 8080
spring:
    datasource:
        password: mehrdad
        url: jdbc:mysql://localhost:3306/task?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
        username: mehrdad
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                format_sql: true
                id:
                    new_generator_mappings: false
