spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/tiny_task?useSSL=false
    username: postgres
    password: mehrdad
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    #database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: true
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    com.metao.persoinfo: DEBUG
server:
  port: 8088
